resolver: lts-15.3
packages:
- .
extra-deps:
- refined-0.4.4
- prettyprinter-1.3.0
- data-default-instances-base-0.1.0.1
- git: git@github.com:muesli4/table-layout.git
  commit: 183b287451ccb52f35b9292cc50d7de81b7b54b5
